name: img_qc
channels:
  - conda-forge
  - defaults
dependencies:
  - ca-certificates=2018.4.16=0
  - certifi=2018.4.16=py36_0
  - freetype=2.8.1=vc14_0
  - icu=58.2=vc14_0
  - jpeg=9b=vc14_2
  - jupyter_contrib_core=0.3.3=py36_1
  - jupyter_contrib_nbextensions=0.5.0=py36_0
  - jupyter_highlight_selected_word=0.2.0=py36_0
  - jupyter_latex_envs=1.4.4=py36_0
  - jupyter_nbextensions_configurator=0.4.0=py36_0
  - libiconv=1.14=vc14_4
  - libpng=1.6.34=vc14_0
  - libsodium=1.0.16=vc14_0
  - libtiff=4.0.9=vc14_0
  - libwebp=0.5.2=vc14_7
  - libxml2=2.9.5=vc14_1
  - libxslt=1.1.32=vc14_0
  - lxml=4.2.1=py36_0
  - matplotlib=2.2.2=py36_1
  - opencv=3.4.1=py36_200
  - openssl=1.0.2o=vc14_0
  - pyyaml=3.12=py36_1
  - qt=5.6.2=vc14_1
  - sqlite=3.22.0=vc14_0
  - winpty=0.4.3=vc14_2
  - yaml=0.1.7=vc14_0
  - zeromq=4.2.5=vc14_1
  - zlib=1.2.11=vc14_0
  - backcall=0.1.0=py36_0
  - bleach=2.1.3=py36_0
  - colorama=0.3.9=py36h029ae33_0
  - cycler=0.10.0=py36h009560c_0
  - decorator=4.3.0=py36_0
  - entrypoints=0.2.3=py36hfd66bb0_2
  - html5lib=1.0.1=py36h047fa9f_0
  - icc_rt=2017.0.4=h97af966_0
  - intel-openmp=2018.0.0=8
  - ipykernel=4.8.2=py36_0
  - ipython=6.3.1=py36_0
  - ipython_genutils=0.2.0=py36h3c5d0ee_0
  - ipywidgets=7.2.1=py36_0
  - jedi=0.12.0=py36_1
  - jinja2=2.10=py36h292fed1_0
  - jsonschema=2.6.0=py36h7636477_0
  - jupyter=1.0.0=py36_4
  - jupyter_client=5.2.3=py36_0
  - jupyter_console=5.2.0=py36h6d89b47_1
  - jupyter_core=4.4.0=py36h56e9d50_0
  - kiwisolver=1.0.1=py36h12c3424_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=1.0=py36h0e26971_1
  - mistune=0.8.3=py36hfa6e2cd_1
  - mkl=2018.0.2=1
  - mkl_fft=1.0.1=py36h452e1ab_0
  - mkl_random=1.0.1=py36h9258bd6_0
  - msys2-conda-epoch=20160418=1
  - nbconvert=5.3.1=py36h8dc0fde_0
  - nbformat=4.4.0=py36h3a5bc1b_0
  - notebook=5.4.1=py36_0
  - numpy=1.14.2=py36h5c71026_1
  - pandas=0.22.0=py36h6538335_0
  - pandoc=1.19.2.1=hb2460c7_1
  - pandocfilters=1.4.2=py36h3ef6317_1
  - parso=0.2.0=py36_0
  - pickleshare=0.7.4=py36h9de030f_0
  - pip=10.0.1=py36_0
  - prompt_toolkit=1.0.15=py36h60b8f86_0
  - pygments=2.2.0=py36hb010967_0
  - pyparsing=2.2.0=py36h785a196_1
  - pyqt=5.6.0=py36_2
  - python=3.6.5=h0c2934d_0
  - python-dateutil=2.7.2=py36_0
  - pytz=2018.4=py36_0
  - pywinpty=0.5.1=py36_0
  - pyzmq=17.0.0=py36hfa6e2cd_1
  - qtconsole=4.3.1=py36h99a29a9_0
  - send2trash=1.5.0=py36_0
  - setuptools=39.1.0=py36_0
  - simplegeneric=0.8.1=py36_2
  - sip=4.19.8=py36h6538335_0
  - six=1.11.0=py36h4db2310_1
  - terminado=0.8.1=py36_1
  - testpath=0.3.1=py36h2698cfe_0
  - tornado=5.0.2=py36_0
  - traitlets=4.3.2=py36h096827d_0
  - vc=14=h0510ff6_3
  - vs2015_runtime=14.0.25123=3
  - wcwidth=0.1.7=py36h3d5aa90_0
  - webencodings=0.5.1=py36h67c50ae_1
  - wheel=0.31.0=py36_0
  - widgetsnbextension=3.2.1=py36_0
  - wincertstore=0.2=py36h7fe50ca_0
  - pip:
    - cython==0.28.2
    - pillow==5.1.0

