name: img_qc
channels:
  - conda-forge
  - defaults
dependencies:
  - ca-certificates=2018.4.16=0
  - certifi=2018.4.16=py36_0
  - jupyter_contrib_core=0.3.3=py36_1
  - jupyter_contrib_nbextensions=0.5.0=py36_0
  - jupyter_highlight_selected_word=0.2.0=py36_0
  - jupyter_latex_envs=1.4.4=py36_0
  - jupyter_nbextensions_configurator=0.4.0=py36_0
  - libxslt=1.1.32=0
  - lxml=4.2.1=py36_0
  - openssl=1.0.2o=0
  - appnope=0.1.0=py36hf537a9a_0
  - backcall=0.1.0=py36_0
  - bleach=2.1.3=py36_0
  - bokeh=0.12.15=py36_0
  - bzip2=1.0.6=hd86a083_4
  - cairo=1.14.12=he60d9cb_2
  - click=6.7=py36hec950be_0
  - cloudpickle=0.5.2=py36_1
  - cycler=0.10.0=py36hfc81398_0
  - cytoolz=0.9.0.1=py36h1de35cc_0
  - dask=0.17.4=py36_0
  - dask-core=0.17.4=py36_0
  - dbus=1.13.2=h760590f_1
  - decorator=4.3.0=py36_0
  - distributed=1.21.8=py36_0
  - entrypoints=0.2.3=py36hd81d71f_2
  - expat=2.2.5=hb8e80ba_0
  - ffmpeg=3.4=h766ddd1_0
  - fontconfig=2.12.6=h9850fc5_0
  - freetype=2.8=h12048fb_1
  - gettext=0.19.8.1=h15daf44_3
  - glib=2.56.1=h35bc53a_0
  - graphite2=1.3.11=h337f25e_1
  - harfbuzz=1.7.6=h171471c_1
  - hdf5=1.10.1=ha036c08_1
  - heapdict=1.0.0=py36_2
  - html5lib=1.0.1=py36h2f9c1c0_0
  - icu=58.2=h4b95b61_1
  - imageio=2.3.0=py36_0
  - intel-openmp=2018.0.0=8
  - ipykernel=4.8.2=py36_0
  - ipython=6.3.1=py36_0
  - ipython_genutils=0.2.0=py36h241746c_0
  - ipywidgets=7.2.1=py36_0
  - jasper=1.900.1=h1f36771_4
  - jedi=0.12.0=py36_1
  - jinja2=2.10=py36hd36f9c5_0
  - jpeg=9b=he5867d9_2
  - jsonschema=2.6.0=py36hb385e00_0
  - jupyter=1.0.0=py36_4
  - jupyter_client=5.2.3=py36_0
  - jupyter_console=5.2.0=py36hccf5b1c_1
  - jupyter_core=4.4.0=py36h79cf704_0
  - kiwisolver=1.0.1=py36h792292d_0
  - libcxx=4.0.1=h579ed51_0
  - libcxxabi=4.0.1=hebd6815_0
  - libedit=3.1=hb4e282d_0
  - libffi=3.2.1=h475c297_4
  - libgfortran=3.0.1=h93005f0_2
  - libiconv=1.15=hdd342a3_7
  - libopus=1.2.1=h169cedb_0
  - libpng=1.6.34=he12f830_0
  - libprotobuf=3.4.1=h326466f_0
  - libsodium=1.0.16=h3efe00b_0
  - libtiff=4.0.9=h0dac147_0
  - libvpx=1.6.1=h057a404_0
  - libxml2=2.9.8=h2866646_0
  - locket=0.2.0=py36hca03003_1
  - markupsafe=1.0=py36h3a1e703_1
  - matplotlib=2.2.2=py36ha7267d0_0
  - mistune=0.8.3=py36h1de35cc_1
  - mkl=2018.0.2=1
  - mkl_fft=1.0.1=py36h917ab60_0
  - mkl_random=1.0.1=py36h78cc56f_0
  - msgpack-python=0.5.6=py36h04f5b5a_0
  - nbconvert=5.3.1=py36h810822e_0
  - nbformat=4.4.0=py36h827af21_0
  - ncurses=6.0=hd04f020_2
  - networkx=2.1=py36_0
  - notebook=5.4.1=py36_0
  - numpy=1.14.2=py36ha9ae307_1
  - olefile=0.45.1=py36_0
  - opencv=3.3.1=py36h60a5f38_1
  - packaging=17.1=py36_0
  - pandas=0.22.0=py36h0a44026_0
  - pandoc=1.19.2.1=ha5e8f32_1
  - pandocfilters=1.4.2=py36h3b0b094_1
  - parso=0.2.0=py36_0
  - partd=0.3.8=py36hf5c4cb8_0
  - pcre=8.42=h378b8a2_0
  - pexpect=4.5.0=py36_0
  - pickleshare=0.7.4=py36hf512f8e_0
  - pillow=5.1.0=py36hfcce615_0
  - pip=10.0.1=py36_0
  - pixman=0.34.0=hca0a616_3
  - prompt_toolkit=1.0.15=py36haeda067_0
  - psutil=5.4.5=py36h1de35cc_0
  - ptyprocess=0.5.2=py36he6521c3_0
  - pygments=2.2.0=py36h240cd3f_0
  - pyparsing=2.2.0=py36hb281f35_0
  - pyqt=5.9.2=py36h11d3b92_0
  - python=3.6.5=hc167b69_1
  - python-dateutil=2.7.2=py36_0
  - pytz=2018.4=py36_0
  - pywavelets=0.5.2=py36h2710a04_0
  - pyyaml=3.12=py36h2ba1e63_1
  - pyzmq=17.0.0=py36h1de35cc_1
  - qt=5.9.5=h02808f3_0
  - qtconsole=4.3.1=py36hd96c0ff_0
  - readline=7.0=hc1231fa_4
  - scikit-image=0.13.1=py36h1de35cc_1
  - scipy=1.0.1=py36hcaad992_0
  - send2trash=1.5.0=py36_0
  - setuptools=39.1.0=py36_0
  - simplegeneric=0.8.1=py36_2
  - sip=4.19.8=py36h0a44026_0
  - six=1.11.0=py36h0e22d5e_1
  - sortedcontainers=1.5.10=py36_0
  - sqlite=3.23.1=hf1716c9_0
  - tblib=1.3.2=py36hda67792_0
  - terminado=0.8.1=py36_1
  - testpath=0.3.1=py36h625a49b_0
  - tk=8.6.7=h35a86e2_3
  - toolz=0.9.0=py36_0
  - tornado=5.0.2=py36_0
  - traitlets=4.3.2=py36h65bd3ce_0
  - wcwidth=0.1.7=py36h8c6ec74_0
  - webencodings=0.5.1=py36h3b9701d_1
  - wheel=0.31.0=py36_0
  - widgetsnbextension=3.2.1=py36_0
  - xz=5.2.3=h727817e_4
  - yaml=0.1.7=hc338f04_2
  - zeromq=4.2.5=h378b8a2_0
  - zict=0.1.3=py36h71da714_0
  - zlib=1.2.11=hf3cbc9b_2
